{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOT4gDIu8mrvOAkazuyMfl8",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Shaquillepj/Data_Warehouse_Indv_Assignment/blob/main/ETL_NYC_MVC.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "fln9gOVSo9zN",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "78da3102-c520-4a62-8912-082243369478"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "100%|██████████| 1/1 [00:00<00:00, 10672.53it/s]\n",
            "100%|██████████| 1/1 [00:00<00:00, 9279.43it/s]\n",
            "100%|██████████| 1/1 [00:00<00:00, 6909.89it/s]\n",
            "100%|██████████| 1/1 [00:00<00:00, 8830.11it/s]\n",
            "100%|██████████| 1/1 [00:00<00:00, 10894.30it/s]\n",
            "100%|██████████| 1/1 [00:00<00:00, 9731.56it/s]\n",
            "100%|██████████| 1/1 [00:00<00:00, 7958.83it/s]\n"
          ]
        }
      ],
      "source": [
        "#--------ENVIRONMENT SETUP--------#\n",
        "from datetime import date\n",
        "\n",
        "#Google Auth\n",
        "from google.colab import auth\n",
        "auth.authenticate_user()\n",
        "import pandas as pd\n",
        "from google.cloud import storage\n",
        "\n",
        "# GCP ID\n",
        "project_id = 'cis9440-indv-assignment'\n",
        "storage_client = storage.Client(project=project_id)\n",
        "\n",
        "# Specific Bucket\n",
        "bucket_name = 'nyc_mvc-bucket'\n",
        "bucket = storage_client.get_bucket(bucket_name)\n",
        "\n",
        "#--------EXTRACTING DATA--------#\n",
        "blob_name = 'nyc_crashes.csv'\n",
        "blob = bucket.blob(blob_name)\n",
        "\n",
        "# Download temp file\n",
        "blob.download_to_filename('/tmp/data.csv')\n",
        "df = pd.read_csv('/tmp/data.csv')\n",
        "\n",
        "\n",
        "#--------TRANSFORMATION--------#\n",
        "# keep only rows with a collision_id and crash_date/time\n",
        "df = df.dropna(subset=[\"collision_id\", \"crash_date\", \"crash_time\"])\n",
        "\n",
        "# collision_id as integer\n",
        "df[\"collision_id\"] = pd.to_numeric(df[\"collision_id\"], errors=\"coerce\")\n",
        "df = df.dropna(subset=[\"collision_id\"])\n",
        "df[\"collision_id\"] = df[\"collision_id\"].astype(\"Int64\")\n",
        "\n",
        "# parse crash datetime\n",
        "dt = pd.to_datetime(df[\"crash_date\"] + \" \" + df[\"crash_time\"], errors=\"coerce\")\n",
        "\n",
        "# unified time pieces for dim_time\n",
        "df[\"clock_time\"] = dt.dt.time\n",
        "df[\"hour\"]       = dt.dt.hour.astype(\"Int64\")\n",
        "df[\"minute\"]     = dt.dt.minute.astype(\"Int64\")\n",
        "\n",
        "# unified date pieces for dim_date\n",
        "df[\"calendar_date\"]  = dt.dt.date\n",
        "df[\"year\"]           = dt.dt.year\n",
        "df[\"month\"]          = dt.dt.month\n",
        "df[\"day\"]            = dt.dt.day.astype(\"Int64\")\n",
        "df[\"weekday\"]        = dt.dt.day_name()\n",
        "\n",
        "# standardize text fields\n",
        "for col in [\"borough\", \"zip_code\"]:\n",
        "    df[col] = df[col].astype(str).str.strip()\n",
        "\n",
        "# replace nan\n",
        "df[\"borough\"] = df[\"borough\"].replace({\"nan\": None, \"\": None}).str.title()\n",
        "\n",
        "street_cols = [\"on_street_name\", \"off_street_name\", \"cross_street_name\"]\n",
        "for col in street_cols:\n",
        "    df[col] = (\n",
        "        df[col]\n",
        "        .astype(str)\n",
        "        .str.strip()\n",
        "        .replace({\"nan\": None, \"\": None})\n",
        "        .str.upper()\n",
        "    )\n",
        "\n",
        "# numeric injury / fatality measures\n",
        "measure_cols = [\n",
        "    \"number_of_persons_injured\",\n",
        "    \"number_of_persons_killed\",\n",
        "    \"number_of_pedestrians_injured\",\n",
        "    \"number_of_pedestrians_killed\",\n",
        "    \"number_of_cyclist_injured\",\n",
        "    \"number_of_cyclist_killed\",\n",
        "    \"number_of_motorist_injured\",\n",
        "    \"number_of_motorist_killed\",\n",
        "]\n",
        "\n",
        "# fill na for numeric columns with 0\n",
        "for col in measure_cols:\n",
        "    df[col] = pd.to_numeric(df[col], errors=\"coerce\").fillna(0).round().astype(\"Int64\")\n",
        "\n",
        "# unify latitude / longitude\n",
        "df[\"latitude\"]  = pd.to_numeric(df[\"latitude\"],  errors=\"coerce\")\n",
        "df[\"longitude\"] = pd.to_numeric(df[\"longitude\"], errors=\"coerce\")\n",
        "\n",
        "# drop collisions where all injury / death counts are zero\n",
        "mask_all_zero = df[measure_cols].fillna(0).eq(0).all(axis=1)\n",
        "df = df[~mask_all_zero].copy()\n",
        "\n",
        "dim_date = (\n",
        "    df[[\"calendar_date\", \"year\", \"month\", \"day\", \"weekday\"]]\n",
        "    .drop_duplicates(subset=[\"calendar_date\"])\n",
        "    .reset_index(drop=True)\n",
        ")\n",
        "\n",
        "# create dim tables\n",
        "dim_date[\"date_key\"] = dim_date.index + 1\n",
        "\n",
        "dim_time = (\n",
        "    df[[\"clock_time\", \"hour\", \"minute\"]]\n",
        "    .drop_duplicates(subset=[\"clock_time\"])\n",
        "    .reset_index(drop=True)\n",
        ")\n",
        "\n",
        "dim_time[\"time_key\"] = dim_time.index\n",
        "\n",
        "dim_location = (\n",
        "    df[[\"borough\", \"zip_code\"]]\n",
        "    .drop_duplicates()\n",
        "    .reset_index(drop=True)\n",
        ")\n",
        "\n",
        "dim_location[\"location_key\"] = dim_location.index + 1\n",
        "\n",
        "dim_street = (\n",
        "    pd.concat([\n",
        "        df[[\"on_street_name\"]].rename(columns={\"on_street_name\": \"street_name\"}),\n",
        "        df[[\"off_street_name\"]].rename(columns={\"off_street_name\": \"street_name\"}),\n",
        "        df[[\"cross_street_name\"]].rename(columns={\"cross_street_name\": \"street_name\"}),\n",
        "    ])\n",
        "    .dropna(subset=[\"street_name\"])\n",
        "    .drop_duplicates()\n",
        "    .reset_index(drop=True)\n",
        ")\n",
        "\n",
        "dim_street[\"street_key\"] = dim_street.index + 1\n",
        "\n",
        "df[\"vehicle_type_code1\"] = (\n",
        "    df[\"vehicle_type_code1\"]\n",
        "    .astype(str)\n",
        "    .str.strip()\n",
        "    .replace({\"nan\": None, \"\": None})\n",
        "    .str.upper()\n",
        ")\n",
        "\n",
        "dim_vehicle_type = (\n",
        "    df[[\"vehicle_type_code1\"]]\n",
        "    .dropna(subset=[\"vehicle_type_code1\"])\n",
        "    .drop_duplicates()\n",
        "    .reset_index(drop=True)\n",
        "    .rename(columns={\"vehicle_type_code1\": \"vehicle_type\"})\n",
        ")\n",
        "\n",
        "dim_vehicle_type[\"vehicle_type_key\"] = dim_vehicle_type.index + 1\n",
        "\n",
        "df[\"contributing_factor_vehicle_1\"] = (\n",
        "    df[\"contributing_factor_vehicle_1\"]\n",
        "    .astype(str)\n",
        "    .str.strip()\n",
        "    .replace({\"nan\": None, \"\": None})\n",
        "    .str.upper()\n",
        ")\n",
        "\n",
        "dim_contributing_factor = (\n",
        "    df[[\"contributing_factor_vehicle_1\"]]\n",
        "    .dropna(subset=[\"contributing_factor_vehicle_1\"])\n",
        "    .drop_duplicates()\n",
        "    .reset_index(drop=True)\n",
        "    .rename(columns={\"contributing_factor_vehicle_1\": \"factor_name\"})\n",
        ")\n",
        "\n",
        "dim_contributing_factor[\"factor_key\"] = dim_contributing_factor.index + 1\n",
        "\n",
        "# Handle Null Foreign Keys-------#\n",
        "\n",
        "# vehicle type\n",
        "unknown_vehicle = pd.DataFrame({\n",
        "    \"vehicle_type\": [\"UNKNOWN\"],\n",
        "    \"vehicle_type_key\": [0]\n",
        "})\n",
        "dim_vehicle_type = pd.concat([unknown_vehicle, dim_vehicle_type], ignore_index=True)\n",
        "\n",
        "# contributing factor\n",
        "unknown_factor = pd.DataFrame({\n",
        "    \"factor_name\": [\"UNKNOWN\"],\n",
        "    \"factor_key\": [0]\n",
        "})\n",
        "dim_contributing_factor = pd.concat([unknown_factor, dim_contributing_factor], ignore_index=True)\n",
        "\n",
        "# street\n",
        "unknown_street = pd.DataFrame({\n",
        "    \"street_name\": [\"UNKNOWN\"],\n",
        "    \"street_key\": [0]\n",
        "})\n",
        "dim_street = pd.concat([unknown_street, dim_street], ignore_index=True)\n",
        "\n",
        "\n",
        "#define ingestion date\n",
        "df[\"ingestion_date\"] = pd.Timestamp(\"today\").normalize()\n",
        "\n",
        "#Attach Keys back to main DF\n",
        "# date_key\n",
        "df = df.merge(\n",
        "    dim_date[[\"calendar_date\", \"date_key\"]],\n",
        "    on=\"calendar_date\",\n",
        "    how=\"left\"\n",
        ")\n",
        "\n",
        "# time_key\n",
        "df = df.merge(\n",
        "    dim_time[[\"clock_time\", \"time_key\"]],\n",
        "    on=\"clock_time\",\n",
        "    how=\"left\"\n",
        ")\n",
        "\n",
        "# location_key\n",
        "df = df.merge(\n",
        "    dim_location[[\"borough\", \"zip_code\", \"location_key\"]],\n",
        "    on=[\"borough\", \"zip_code\"],\n",
        "    how=\"left\"\n",
        ")\n",
        "\n",
        "# street keys\n",
        "df = df.merge(\n",
        "    dim_street[[\"street_name\", \"street_key\"]],\n",
        "    left_on=\"on_street_name\",\n",
        "    right_on=\"street_name\",\n",
        "    how=\"left\"\n",
        ").rename(columns={\"street_key\": \"on_street_key\"}).drop(columns=[\"street_name\"])\n",
        "\n",
        "df = df.merge(\n",
        "    dim_street[[\"street_name\", \"street_key\"]],\n",
        "    left_on=\"off_street_name\",\n",
        "    right_on=\"street_name\",\n",
        "    how=\"left\"\n",
        ").rename(columns={\"street_key\": \"off_street_key\"}).drop(columns=[\"street_name\"])\n",
        "\n",
        "df = df.merge(\n",
        "    dim_street[[\"street_name\", \"street_key\"]],\n",
        "    left_on=\"cross_street_name\",\n",
        "    right_on=\"street_name\",\n",
        "    how=\"left\"\n",
        ").rename(columns={\"street_key\": \"cross_street_key\"}).drop(columns=[\"street_name\"])\n",
        "\n",
        "# vehicle_type_key\n",
        "df = df.merge(\n",
        "    dim_vehicle_type[[\"vehicle_type\", \"vehicle_type_key\"]],\n",
        "    left_on=\"vehicle_type_code1\",\n",
        "    right_on=\"vehicle_type\",\n",
        "    how=\"left\"\n",
        ").drop(columns=[\"vehicle_type\"])\n",
        "\n",
        "# factor_key\n",
        "df = df.merge(\n",
        "    dim_contributing_factor[[\"factor_name\", \"factor_key\"]],\n",
        "    left_on=\"contributing_factor_vehicle_1\",\n",
        "    right_on=\"factor_name\",\n",
        "    how=\"left\"\n",
        ").drop(columns=[\"factor_name\"])\n",
        "\n",
        "\n",
        "# Build Fact Table\n",
        "fact_collision = df[[\n",
        "    \"collision_id\",\n",
        "    \"vehicle_type_key\",\n",
        "    \"factor_key\",\n",
        "    \"date_key\",\n",
        "    \"time_key\",\n",
        "    \"location_key\",\n",
        "    \"on_street_key\",\n",
        "    \"cross_street_key\",\n",
        "    \"off_street_key\",\n",
        "    \"number_of_persons_injured\",\n",
        "    \"number_of_persons_killed\",\n",
        "    \"number_of_pedestrians_injured\",\n",
        "    \"number_of_pedestrians_killed\",\n",
        "    \"number_of_cyclist_injured\",\n",
        "    \"number_of_cyclist_killed\",\n",
        "    \"number_of_motorist_injured\",\n",
        "    \"number_of_motorist_killed\",\n",
        "    \"latitude\",\n",
        "    \"longitude\",\n",
        "    \"ingestion_date\",\n",
        "]].copy()\n",
        "\n",
        "# surrogate key\n",
        "fact_collision = fact_collision.reset_index(drop=True)\n",
        "fact_collision[\"collision_key\"] = fact_collision.index + 1\n",
        "\n",
        "fact_collision = fact_collision[[\n",
        "    \"collision_key\",\n",
        "    \"collision_id\",\n",
        "    \"vehicle_type_key\",\n",
        "    \"factor_key\",\n",
        "    \"date_key\",\n",
        "    \"time_key\",\n",
        "    \"location_key\",\n",
        "    \"on_street_key\",\n",
        "    \"cross_street_key\",\n",
        "    \"off_street_key\",\n",
        "    \"number_of_persons_injured\",\n",
        "    \"number_of_persons_killed\",\n",
        "    \"number_of_pedestrians_injured\",\n",
        "    \"number_of_pedestrians_killed\",\n",
        "    \"number_of_cyclist_injured\",\n",
        "    \"number_of_cyclist_killed\",\n",
        "    \"number_of_motorist_injured\",\n",
        "    \"number_of_motorist_killed\",\n",
        "    \"latitude\",\n",
        "    \"longitude\",\n",
        "    \"ingestion_date\",\n",
        "]]\n",
        "\n",
        "\n",
        "#--------DATA LOADING--------#\n",
        "# BigQuery Set up\n",
        "project_id = \"cis9440-indv-assignment\"\n",
        "dataset_id = \"nyc_mvc_star\"\n",
        "# !pip install pandas-gbq --quiet\n",
        "\n",
        "from pandas_gbq import to_gbq\n",
        "\n",
        "# Load Dimensions Table\n",
        "to_gbq(\n",
        "    dim_date,\n",
        "    f\"{dataset_id}.dim_date\",\n",
        "    project_id=project_id,\n",
        "    if_exists=\"replace\"\n",
        ")\n",
        "\n",
        "to_gbq(\n",
        "    dim_time,\n",
        "    f\"{dataset_id}.dim_time\",\n",
        "    project_id=project_id,\n",
        "    if_exists=\"replace\"\n",
        ")\n",
        "\n",
        "to_gbq(\n",
        "    dim_location,\n",
        "    f\"{dataset_id}.dim_location\",\n",
        "    project_id=project_id,\n",
        "    if_exists=\"replace\"\n",
        ")\n",
        "\n",
        "to_gbq(\n",
        "    dim_street,\n",
        "    f\"{dataset_id}.dim_street\",\n",
        "    project_id=project_id,\n",
        "    if_exists=\"replace\"\n",
        ")\n",
        "\n",
        "to_gbq(\n",
        "    dim_vehicle_type,\n",
        "    f\"{dataset_id}.dim_vehicle_type\",\n",
        "    project_id=project_id,\n",
        "    if_exists=\"replace\"\n",
        ")\n",
        "\n",
        "to_gbq(\n",
        "    dim_contributing_factor,\n",
        "    f\"{dataset_id}.dim_contributing_factor\",\n",
        "    project_id=project_id,\n",
        "    if_exists=\"replace\"\n",
        ")\n",
        "\n",
        "#Load fact table\n",
        "to_gbq(fact_collision,\n",
        "    f\"{dataset_id}.fact_collision\",\n",
        "    project_id=project_id,\n",
        "    if_exists=\"replace\"\n",
        ")"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import pandas as pd\n",
        "\n",
        "rows = [\n",
        "\n",
        "    # ===== dim_date =====\n",
        "    {\n",
        "        \"table_name\": \"dim_date\",\n",
        "        \"column_name\": \"date_key\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Surrogate key for the calendar date\",\n",
        "        \"source_column\": \"N/A\",\n",
        "        \"transformation\": \"Sequential index per distinct calendar_date\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"dim_date\",\n",
        "        \"column_name\": \"calendar_date\",\n",
        "        \"data_type\": \"DATE\",\n",
        "        \"description\": \"Occurrence date of collision\",\n",
        "        \"source_column\": \"CRASH DATE\",\n",
        "        \"transformation\": \"CRASH DATE and CRASH TIME parsed to datetime, date part only\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"dim_date\",\n",
        "        \"column_name\": \"year\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Year extracted from crash date\",\n",
        "        \"source_column\": \"CRASH DATE\",\n",
        "        \"transformation\": \"Year from parsed crash datetime\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"dim_date\",\n",
        "        \"column_name\": \"month\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Month extracted from crash date\",\n",
        "        \"source_column\": \"CRASH DATE\",\n",
        "        \"transformation\": \"Month from parsed crash datetime\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"dim_date\",\n",
        "        \"column_name\": \"day\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Day of month extracted from crash date\",\n",
        "        \"source_column\": \"CRASH DATE\",\n",
        "        \"transformation\": \"Day from parsed crash datetime\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"dim_date\",\n",
        "        \"column_name\": \"weekday\",\n",
        "        \"data_type\": \"STRING\",\n",
        "        \"description\": \"Day of week name for crash date\",\n",
        "        \"source_column\": \"CRASH DATE\",\n",
        "        \"transformation\": \"Day name from parsed crash datetime\"\n",
        "    },\n",
        "\n",
        "    # ===== dim_time =====\n",
        "    {\n",
        "        \"table_name\": \"dim_time\",\n",
        "        \"column_name\": \"time_key\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Surrogate key for time of day\",\n",
        "        \"source_column\": \"N/A\",\n",
        "        \"transformation\": \"Sequential index per distinct clock_time\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"dim_time\",\n",
        "        \"column_name\": \"clock_time\",\n",
        "        \"data_type\": \"TIME\",\n",
        "        \"description\": \"Occurrence time of collision\",\n",
        "        \"source_column\": \"CRASH TIME\",\n",
        "        \"transformation\": \"CRASH DATE and CRASH TIME parsed to datetime, time part only\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"dim_time\",\n",
        "        \"column_name\": \"hour\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Hour part of crash time\",\n",
        "        \"source_column\": \"CRASH TIME\",\n",
        "        \"transformation\": \"Hour from parsed crash datetime\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"dim_time\",\n",
        "        \"column_name\": \"minute\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Minute part of crash time\",\n",
        "        \"source_column\": \"CRASH TIME\",\n",
        "        \"transformation\": \"Minute from parsed crash datetime\"\n",
        "    },\n",
        "\n",
        "    # ===== dim_location =====\n",
        "    {\n",
        "        \"table_name\": \"dim_location\",\n",
        "        \"column_name\": \"location_key\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Surrogate key for location\",\n",
        "        \"source_column\": \"N/A\",\n",
        "        \"transformation\": \"Sequential index per distinct combination of BOROUGH and ZIP CODE\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"dim_location\",\n",
        "        \"column_name\": \"borough\",\n",
        "        \"data_type\": \"STRING\",\n",
        "        \"description\": \"Borough where collision occurred\",\n",
        "        \"source_column\": \"BOROUGH\",\n",
        "        \"transformation\": \"Cast to string, trim spaces, blank or 'nan' set to null, title case\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"dim_location\",\n",
        "        \"column_name\": \"zip_code\",\n",
        "        \"data_type\": \"STRING\",\n",
        "        \"description\": \"Postal code of incident occurrence\",\n",
        "        \"source_column\": \"ZIP CODE\",\n",
        "        \"transformation\": \"Cast to string, trim spaces, blank or 'nan' set to null, optionally padded to 5 digits\"\n",
        "    },\n",
        "\n",
        "    # ===== dim_street =====\n",
        "    {\n",
        "        \"table_name\": \"dim_street\",\n",
        "        \"column_name\": \"street_key\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Surrogate key for street name\",\n",
        "        \"source_column\": \"N/A\",\n",
        "        \"transformation\": \"Sequential index per distinct street_name, plus UNKNOWN with key 0\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"dim_street\",\n",
        "        \"column_name\": \"street_name\",\n",
        "        \"data_type\": \"STRING\",\n",
        "        \"description\": \"Street or intersection name associated with the collision\",\n",
        "        \"source_column\": \"ON STREET NAME, CROSS STREET NAME, OFF STREET NAME\",\n",
        "        \"transformation\": \"Union of street columns, cast to string, trim, uppercase, drop null, add UNKNOWN\"\n",
        "    },\n",
        "\n",
        "    # ===== dim_vehicle_type =====\n",
        "    {\n",
        "        \"table_name\": \"dim_vehicle_type\",\n",
        "        \"column_name\": \"vehicle_type_key\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Surrogate key for vehicle type\",\n",
        "        \"source_column\": \"N/A\",\n",
        "        \"transformation\": \"Sequential index per distinct vehicle_type, plus UNKNOWN with key 0\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"dim_vehicle_type\",\n",
        "        \"column_name\": \"vehicle_type\",\n",
        "        \"data_type\": \"STRING\",\n",
        "        \"description\": \"Type of vehicle based on the selected vehicle category\",\n",
        "        \"source_column\": \"VEHICLE TYPE CODE 1\",\n",
        "        \"transformation\": \"Cast to string, trim, uppercase, blank or 'nan' set to null\"\n",
        "    },\n",
        "\n",
        "    # ===== dim_contributing_factor =====\n",
        "    {\n",
        "        \"table_name\": \"dim_contributing_factor\",\n",
        "        \"column_name\": \"factor_key\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Surrogate key for contributing factor\",\n",
        "        \"source_column\": \"N/A\",\n",
        "        \"transformation\": \"Sequential index per distinct factor_name, plus UNKNOWN with key 0\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"dim_contributing_factor\",\n",
        "        \"column_name\": \"factor_name\",\n",
        "        \"data_type\": \"STRING\",\n",
        "        \"description\": \"Factors contributing to the collision for designated vehicle\",\n",
        "        \"source_column\": \"CONTRIBUTING FACTOR VEHICLE 1\",\n",
        "        \"transformation\": \"Cast to string, trim, uppercase, blank or 'nan' set to null\"\n",
        "    },\n",
        "\n",
        "    # ===== fact_collision =====\n",
        "    {\n",
        "        \"table_name\": \"fact_collision\",\n",
        "        \"column_name\": \"collision_key\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Surrogate key for collision fact row\",\n",
        "        \"source_column\": \"N/A\",\n",
        "        \"transformation\": \"Sequential index over fact rows after cleaning\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"fact_collision\",\n",
        "        \"column_name\": \"collision_id\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Unique record code generated by system\",\n",
        "        \"source_column\": \"COLLISION_ID\",\n",
        "        \"transformation\": \"Convert to numeric, drop nulls, cast to integer\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"fact_collision\",\n",
        "        \"column_name\": \"vehicle_type_key\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Foreign key to dim_vehicle_type\",\n",
        "        \"source_column\": \"VEHICLE TYPE CODE 1\",\n",
        "        \"transformation\": \"Join on cleaned vehicle_type to dim_vehicle_type, nulls filled with 0\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"fact_collision\",\n",
        "        \"column_name\": \"factor_key\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Foreign key to dim_contributing_factor\",\n",
        "        \"source_column\": \"CONTRIBUTING FACTOR VEHICLE 1\",\n",
        "        \"transformation\": \"Join on cleaned factor_name to dim_contributing_factor, nulls filled with 0\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"fact_collision\",\n",
        "        \"column_name\": \"date_key\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Foreign key to dim_date\",\n",
        "        \"source_column\": \"CRASH DATE\",\n",
        "        \"transformation\": \"Join on calendar_date in dim_date\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"fact_collision\",\n",
        "        \"column_name\": \"time_key\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Foreign key to dim_time\",\n",
        "        \"source_column\": \"CRASH TIME\",\n",
        "        \"transformation\": \"Join on clock_time in dim_time\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"fact_collision\",\n",
        "        \"column_name\": \"location_key\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Foreign key to dim_location\",\n",
        "        \"source_column\": \"BOROUGH, ZIP CODE\",\n",
        "        \"transformation\": \"Join on cleaned BOROUGH and ZIP CODE\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"fact_collision\",\n",
        "        \"column_name\": \"on_street_key\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Foreign key to dim_street for on street name\",\n",
        "        \"source_column\": \"ON STREET NAME\",\n",
        "        \"transformation\": \"Join to dim_street.street_name, nulls filled with 0 (UNKNOWN)\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"fact_collision\",\n",
        "        \"column_name\": \"cross_street_key\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Foreign key to dim_street for cross street name\",\n",
        "        \"source_column\": \"CROSS STREET NAME\",\n",
        "        \"transformation\": \"Join to dim_street.street_name, nulls filled with 0 (UNKNOWN)\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"fact_collision\",\n",
        "        \"column_name\": \"off_street_key\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Foreign key to dim_street for off street name\",\n",
        "        \"source_column\": \"OFF STREET NAME\",\n",
        "        \"transformation\": \"Join to dim_street.street_name, nulls filled with 0 (UNKNOWN)\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"fact_collision\",\n",
        "        \"column_name\": \"number_of_persons_injured\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Number of persons injured\",\n",
        "        \"source_column\": \"NUMBER OF PERSONS INJURED\",\n",
        "        \"transformation\": \"Convert to numeric, null to 0, round, cast to integer\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"fact_collision\",\n",
        "        \"column_name\": \"number_of_persons_killed\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Number of persons killed\",\n",
        "        \"source_column\": \"NUMBER OF PERSONS KILLED\",\n",
        "        \"transformation\": \"Convert to numeric, null to 0, round, cast to integer\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"fact_collision\",\n",
        "        \"column_name\": \"number_of_pedestrians_injured\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Number of pedestrians injured\",\n",
        "        \"source_column\": \"NUMBER OF PEDESTRIANS INJURED\",\n",
        "        \"transformation\": \"Convert to numeric, null to 0, round, cast to integer\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"fact_collision\",\n",
        "        \"column_name\": \"number_of_pedestrians_killed\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Number of pedestrians killed\",\n",
        "        \"source_column\": \"NUMBER OF PEDESTRIANS KILLED\",\n",
        "        \"transformation\": \"Convert to numeric, null to 0, round, cast to integer\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"fact_collision\",\n",
        "        \"column_name\": \"number_of_cyclist_injured\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Number of cyclists injured\",\n",
        "        \"source_column\": \"NUMBER OF CYCLIST INJURED\",\n",
        "        \"transformation\": \"Convert to numeric, null to 0, round, cast to integer\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"fact_collision\",\n",
        "        \"column_name\": \"number_of_cyclist_killed\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Number of cyclists killed\",\n",
        "        \"source_column\": \"NUMBER OF CYCLIST KILLED\",\n",
        "        \"transformation\": \"Convert to numeric, null to 0, round, cast to integer\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"fact_collision\",\n",
        "        \"column_name\": \"number_of_motorist_injured\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Number of vehicle occupants injured\",\n",
        "        \"source_column\": \"NUMBER OF MOTORIST INJURED\",\n",
        "        \"transformation\": \"Convert to numeric, null to 0, round, cast to integer\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"fact_collision\",\n",
        "        \"column_name\": \"number_of_motorist_killed\",\n",
        "        \"data_type\": \"INT64\",\n",
        "        \"description\": \"Number of vehicle occupants killed\",\n",
        "        \"source_column\": \"NUMBER OF MOTORIST KILLED\",\n",
        "        \"transformation\": \"Convert to numeric, null to 0, round, cast to integer\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"fact_collision\",\n",
        "        \"column_name\": \"latitude\",\n",
        "        \"data_type\": \"FLOAT64\",\n",
        "        \"description\": \"Latitude coordinate for Global Coordinate System WGS 1984\",\n",
        "        \"source_column\": \"LATITUDE\",\n",
        "        \"transformation\": \"Convert to numeric with errors set to null\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"fact_collision\",\n",
        "        \"column_name\": \"longitude\",\n",
        "        \"data_type\": \"FLOAT64\",\n",
        "        \"description\": \"Longitude coordinate for Global Coordinate System WGS 1984\",\n",
        "        \"source_column\": \"LONGITUDE\",\n",
        "        \"transformation\": \"Convert to numeric with errors set to null\"\n",
        "    },\n",
        "    {\n",
        "        \"table_name\": \"fact_collision\",\n",
        "        \"column_name\": \"ingestion_date\",\n",
        "        \"data_type\": \"DATE\",\n",
        "        \"description\": \"Date when the record was ingested into the warehouse\",\n",
        "        \"source_column\": \"N/A\",\n",
        "        \"transformation\": \"Set in ETL to current date\"\n",
        "    },\n",
        "\n",
        "]\n",
        "\n",
        "dd_df = pd.DataFrame(rows)\n",
        "dd_df.to_csv(\"nyc_mvc_data_dictionary.csv\", index=False)\n",
        "print(\"Wrote nyc_mvc_data_dictionary.csv\")"
      ],
      "metadata": {
        "id": "TruASr3R0XKB",
        "outputId": "a331a17c-f887-4925-ced3-d51f09e08f77",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Wrote nyc_mvc_data_dictionary.csv\n"
          ]
        }
      ]
    }
  ]
}